// Package follower generates per-container overlay config files for
// gravwell_file_follow and writes them atomically to the conf.d directory.
package follower

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

const confTemplate = `# Auto-generated by docker-log-watcher — DO NOT EDIT
# Container: %s (%s)
# Generated: %s

[Follower "%s"]
	Base-Directory="%s"
	File-Filter="%s"
	Tag-Name=%s
	Assume-Local-Timezone=false
	Ignore-Timestamps=false
	Recursive=false
%s`

var nonAlphanumRE = regexp.MustCompile(`[^a-zA-Z0-9_-]`)

// Generator manages the lifecycle of per-container conf files in a directory.
type Generator struct {
	confDir           string
	containerDir      string
	logSubdir         string // appended after <containerDir>/<id>; "" for Docker, "userdata" for Podman
	defaultFileFilter string // glob when no label override; "*-json.log" for Docker, "*.log" for Podman
}

// NewGenerator creates a Generator with Docker defaults (backward-compatible).
func NewGenerator(confDir, containerDir string) *Generator {
	return NewGeneratorWithBackend(confDir, containerDir, "", "")
}

// NewGeneratorWithBackend creates a Generator with explicit backend-specific
// defaults.  logSubdir is appended to <containerDir>/<id> to reach the log
// directory (empty for Docker, "userdata" for Podman).  defaultFileFilter is
// the glob used when no gravwell.log-filter label is present (empty falls back
// to "*-json.log").
func NewGeneratorWithBackend(confDir, containerDir, logSubdir, defaultFileFilter string) *Generator {
	if defaultFileFilter == "" {
		defaultFileFilter = "*-json.log"
	}
	return &Generator{
		confDir:           confDir,
		containerDir:      containerDir,
		logSubdir:         logSubdir,
		defaultFileFilter: defaultFileFilter,
	}
}

// Write generates a config file for the given container and atomically writes it
// to confDir/<sanitizedName>.conf.  It returns the path written.
//
// logDir overrides the Base-Directory (defaults to containerDir/containerID).
// fileFilter overrides the File-Filter glob (defaults to "*-json.log").
// persist, when true, writes a sibling <sanitizedName>.persist marker so the
// config survives container destroy events (useful for named-volume log sources
// that outlive the container).  When false any existing marker is removed,
// clearing a previously set persist flag.
// persistTTL, when > 0, stores the TTL duration in the persist marker so the
// config is eventually cleaned up after the container has been gone that long.
// Any existing .expiry file is cleared on Write so a restarted container resets
// the countdown.
// timestampRegex and timestampFormat, when both non-empty, are written as
// Timestamp-Regex and Timestamp-Format-String in the follower stanza.
func (g *Generator) Write(containerID, containerName, tag, logDir, fileFilter string, persist bool, persistTTL time.Duration, timestampRegex, timestampFormat string) (string, error) {
	safeName := SanitizeName(containerName)
	if logDir == "" {
		logDir = filepath.Join(g.containerDir, containerID)
		if g.logSubdir != "" {
			logDir = filepath.Join(logDir, g.logSubdir)
		}
	}
	if fileFilter == "" {
		fileFilter = g.defaultFileFilter
	}

	var tsExtra string
	if timestampRegex != "" && timestampFormat != "" {
		tsExtra = fmt.Sprintf("\tTimestamp-Regex=`%s`\n\tTimestamp-Format-String=%q\n", timestampRegex, timestampFormat)
	}

	content := fmt.Sprintf(
		confTemplate,
		containerName, containerID,
		time.Now().UTC().Format(time.RFC3339),
		safeName,
		logDir,
		fileFilter,
		tag,
		tsExtra,
	)

	confPath := filepath.Join(g.confDir, safeName+".conf")
	tmpPath := confPath + ".tmp"

	if err := os.WriteFile(tmpPath, []byte(content), 0640); err != nil {
		return "", fmt.Errorf("write tmp config: %w", err)
	}
	if err := os.Rename(tmpPath, confPath); err != nil {
		_ = os.Remove(tmpPath)
		return "", fmt.Errorf("rename config: %w", err)
	}

	markerPath := filepath.Join(g.confDir, safeName+".persist")
	expiryPath := filepath.Join(g.confDir, safeName+".expiry")
	if persist {
		// Store the TTL duration string in the marker (empty = persist forever).
		ttlStr := ""
		if persistTTL > 0 {
			ttlStr = persistTTL.String()
		}
		if err := os.WriteFile(markerPath, []byte(ttlStr), 0640); err != nil {
			return confPath, fmt.Errorf("write persist marker: %w", err)
		}
		// Container (re)started — clear any pending expiry so the TTL resets.
		_ = os.Remove(expiryPath)
	} else {
		_ = os.Remove(markerPath)
		_ = os.Remove(expiryPath)
	}

	return confPath, nil
}

// Remove deletes the config file and all sidecar files (.persist, .expiry) for
// the given container name.  It returns (true, nil) when the config was deleted,
// (false, nil) when it did not exist (no-op), or (false, err) on a real
// filesystem error.
func (g *Generator) Remove(containerName string) (bool, error) {
	safeName := SanitizeName(containerName)
	confPath := filepath.Join(g.confDir, safeName+".conf")
	err := os.Remove(confPath)
	if os.IsNotExist(err) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	_ = os.Remove(filepath.Join(g.confDir, safeName+".persist"))
	_ = os.Remove(filepath.Join(g.confDir, safeName+".expiry"))
	return true, nil
}

// IsPersisted reports whether containerName has a persist marker, meaning its
// config should survive container destroy events.
func (g *Generator) IsPersisted(containerName string) bool {
	safeName := SanitizeName(containerName)
	_, err := os.Stat(filepath.Join(g.confDir, safeName+".persist"))
	return err == nil
}

// PersistTTL returns the TTL duration stored in the persist marker for
// containerName.  Returns 0 if there is no TTL (persist forever) or if the
// marker does not exist.
func (g *Generator) PersistTTL(containerName string) time.Duration {
	safeName := SanitizeName(containerName)
	data, err := os.ReadFile(filepath.Join(g.confDir, safeName+".persist"))
	if err != nil || len(data) == 0 {
		return 0
	}
	d, err := time.ParseDuration(strings.TrimSpace(string(data)))
	if err != nil {
		return 0
	}
	return d
}

// SetExpiry writes the absolute expiry time for containerName to a .expiry
// sidecar file.  This is called at destroy-time so the expiry survives watcher
// restarts.
func (g *Generator) SetExpiry(containerName string, t time.Time) error {
	safeName := SanitizeName(containerName)
	return os.WriteFile(
		filepath.Join(g.confDir, safeName+".expiry"),
		[]byte(t.UTC().Format(time.RFC3339)),
		0640,
	)
}

// ReadExpiry returns the expiry time stored by SetExpiry.  Returns the zero
// Time and false if no expiry file exists or it cannot be parsed.
func (g *Generator) ReadExpiry(containerName string) (time.Time, bool) {
	safeName := SanitizeName(containerName)
	data, err := os.ReadFile(filepath.Join(g.confDir, safeName+".expiry"))
	if err != nil {
		return time.Time{}, false
	}
	t, err := time.Parse(time.RFC3339, strings.TrimSpace(string(data)))
	if err != nil {
		return time.Time{}, false
	}
	return t, true
}

// Exists reports whether a config file already exists for containerName.
func (g *Generator) Exists(containerName string) bool {
	safeName := SanitizeName(containerName)
	_, err := os.Stat(filepath.Join(g.confDir, safeName+".conf"))
	return err == nil
}

// ListConfigs returns the sanitised names of all .conf files currently in
// confDir (i.e. the names that were passed to Write).  Each entry has had
// SanitizeName applied and the ".conf" suffix stripped.
func (g *Generator) ListConfigs() ([]string, error) {
	entries, err := os.ReadDir(g.confDir)
	if err != nil {
		return nil, fmt.Errorf("read conf dir: %w", err)
	}
	var names []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if strings.HasSuffix(name, ".conf") {
			names = append(names, strings.TrimSuffix(name, ".conf"))
		}
	}
	return names, nil
}

// SanitizeName converts a container name into a filesystem/config-safe string.
// Leading "/" is stripped (Docker convention), then any character that is not
// alphanumeric, "-", or "_" is replaced with "_".
func SanitizeName(name string) string {
	name = strings.TrimPrefix(name, "/")
	return nonAlphanumRE.ReplaceAllString(name, "_")
}

// TagFromName derives the Gravwell tag from a container name.  It applies the
// same sanitisation rules so the tag is always valid.
func TagFromName(name string) string {
	return SanitizeName(name)
}
